# Generated by Django 3.1.7 on 2021-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category_type',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
