# Generated by Django 3.1.7 on 2021-04-05 06:34

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210405_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lable',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('NA', 'New Arrival'), ('BS', 'Best Seller')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category_type'),
        ),
        migrations.AlterField(
            model_name='product_color',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
