# Generated by Django 3.1.7 on 2021-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210410_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='type',
            field=models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='billing',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='billing',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='locality',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pin',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='billing',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
